/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Classes.EscritorLector;
import Classes.Grafo;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class Interfaz extends javax.swing.JFrame {
    private Grafo grafo;
    private EscritorLector el;
    private Menu menu;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);       
    }

    public void setGrafo(Grafo grafo) {
        this.grafo = grafo;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    public void setEl(EscritorLector el) {
        this.el = el;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reporte = new javax.swing.JButton();
        pedido = new javax.swing.JButton();
        nuevoAlm = new javax.swing.JButton();
        gestion = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reporte.setText("Reporte de disponibilidad");
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });
        jPanel1.add(reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        pedido.setText("Hacer Pedido");
        pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoActionPerformed(evt);
            }
        });
        jPanel1.add(pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        nuevoAlm.setText("Agregar almacen");
        nuevoAlm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAlmActionPerformed(evt);
            }
        });
        jPanel1.add(nuevoAlm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        gestion.setText("Gestionar productos");
        gestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionActionPerformed(evt);
            }
        });
        jPanel1.add(gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 30));

        guardar.setText("Guardar cambios");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jButton1.setText("Usar otra base de datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
        this.grafo.reportePorAnchura();
    }//GEN-LAST:event_reporteActionPerformed

    private void pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoActionPerformed
        grafo.pedido();
    }//GEN-LAST:event_pedidoActionPerformed

    private void nuevoAlmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAlmActionPerformed
        grafo.nuevoAlm();
    }//GEN-LAST:event_nuevoAlmActionPerformed

    private void gestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionActionPerformed
        try{
            int alm = Integer.parseInt(JOptionPane.showInputDialog(null, ("A qué almacen desea agregar productos"+grafo.getAlmacenes().info())));
            if(alm <0 || alm>grafo.getSize()-1){
                JOptionPane.showMessageDialog(null, "Valor no válido");
            }else{
                grafo.agregarStock(alm);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Valor no válido");
        }
    }//GEN-LAST:event_gestionActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        this.el.escritura(grafo);
    }//GEN-LAST:event_guardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.menu.setVisible(true);
        this.setVisible(false);
        this.setGrafo(new Grafo(26));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gestion;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nuevoAlm;
    private javax.swing.JButton pedido;
    private javax.swing.JButton reporte;
    // End of variables declaration//GEN-END:variables
}
